artcraftV2/artcraftV2/artcraft/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name = 'artcraft'

urlpatterns = [
    path('index/', views.homeView.as_view(), name="home"),
    path('dashboard/', views.dashboardView.as_view(), name="dashboard"),
    path('login/', views.loginView.as_view(), name="login"), 
    path('register/', views.registerView.as_view(), name="register"),
    path('registerArtist/', views.registerArtistView.as_view(), name="registerArtist"),
    path('about/', views.aboutView.as_view(), name="about"),
    path('artwork/', views.artworkView.as_view(), name="artwork"),
    path('contact/', views.contactView.as_view(), name="contact"),
]

artcraftV2/artcraftV2/artcraftV2/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('artcraft/', include('artcraft.urls', namespace='artcraft')),
]

artcraftV2/artcraftV2/artcraft/models.py
from django.db import models

# Create your models here.

class Artist(models.Model):
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    birthDate = models.DateField()
    address = models.CharField(max_length=50)
    phoneNumber = models.CharField(max_length=20)
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)

    class Meta:
        db_table = "Artist"
        

class Customer(models.Model):
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=50)
    phoneNumber = models.CharField(max_length=20)
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=20)

    class Meta:
        db_table = "Customer"

class Artwork(models.Model):
    year = models.DateField(max_length=50)
    title = models.CharField(max_length=50)
    price = models.IntegerField()
    type = models.CharField(max_length=50)
    description = models.CharField(max_length=250)
    artistID = models.ForeignKey(Artist, on_delete=models.CASCADE)

    class Meta:
        db_table = "Artwork"
        

class Order(models.Model):
    orderPrice = models.IntegerField() # there will be a shipping fee teehee
    orderDate = models.DateField(max_length=20)
    artworkID = models.ForeignKey(Artwork, on_delete=models.CASCADE)
    customerID = models.ForeignKey(Customer, on_delete=models.CASCADE)

    class Meta:
        db_table = "Order"
        

artcraftV2/artcraftV2/artcraft/forms.py
from django import forms
from django.db.models import fields
from django.db.models.base import Model
from .models import *


class ArtistForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = ('firstName','lastName','birthDate','address','phoneNumber','username','password')

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('firstName','lastName', 'email', 'address', 'phoneNumber', 'username', 'password')

class ArtworkForm(forms.ModelForm):
    class Meta:
        model = Artwork
        fields = ( 'year', 'title', 'price','type', 'description', 'artistID')

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('orderPrice','orderDate','artworkID','customerID')

artcraftV2/artcraftV2/artcraft/views.py
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import View
from .forms import *
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
# Create your views here.

class homeView(View):
    def get(self, request):
        
        return render(request, 'home.html')

class aboutView(View):
    def get(self, request):
        
        return render(request, 'about.html')

class artworkView(View):
    def get(self, request):
        
        return render(request, 'artwork.html')

class contactView(View):
    def get(self, request):
        
        return render(request, 'contact.html')      

class dashboardView(View):
    def get(self, request):
        qs_artist = Artist.objects.all()
        qs_customer = Customer.objects.all()
    
        context = {
            'artist' : qs_artist,
            'customer' : qs_customer
        }
        
        return render(request, 'dashboard.html', context)

    def post(self, request):
        if request.method == 'POST':
            # Artist
            if 'btnUpdate' in request.POST:
                print('update button clicked')
                id = request.POST.get("id")
                fname = request.POST.get("firstName")
                lname = request.POST.get("lastName")
                bDate = request.POST.get("birthDate")
                address = request.POST.get("address")
                phone = request.POST.get("phoneNumber")

                update_artist = Artist.objects.filter(id = id).update(firstName = fname, lastName = lname, birthDate=bDate, address=address, phoneNumber=phone)

                print(update_artist)
                return redirect('artcraft:dashboard')

            elif 'btnDelete' in request.POST:
                print('delete button clicked')
                id = request.POST.get("id")
                artist = Artist.objects.filter(id = id).delete()

                return redirect('artcraft:dashboard')

            # Customer
            elif 'btnUpdate2' in request.POST:
                print('update button clicked')
                id = request.POST.get("id")
                fname = request.POST.get("firstName")
                lname = request.POST.get("lastName")
                email = request.POST.get("email")
                address = request.POST.get("address")
                phone = request.POST.get("phoneNumber")

                update_customer = Customer.objects.filter(id = id).update(firstName = fname, lastName = lname, email=email, address=address, phoneNumber=phone)

                print(update_customer)
                return redirect('artcraft:dashboard')

            elif 'btnDelete2' in request.POST:
                print('delete button clicked')
                id = request.POST.get("id")
                customer = Customer.objects.filter(id = id).delete()

                return redirect('artcraft:dashboard')

class loginView(View):
    def get(self, request):
        return render(request, 'login.html')

    def post(self, request):
        uname = request.POST.get('username')
        pwd = request.POST.get('password')

        if Customer.objects.filter(username=uname).count() != 0:
            account = Customer.objects.get(username=uname)

            if account.password == pwd:
                return redirect('artcraft:home')
            else:
                messages.error(request, 'Incorrect Password')
        else:
            messages.error(request, 'Username Does Not Exist')

        return render(request, 'login.html')

def LogoutView(request):
	logout(request)
	return redirect('artcraft:login')


class registerView(View):
    def get(self, request):
        return render(request, 'register.html')
    
    def post(self, request):
        form = CustomerForm(request.POST)

        if form.is_valid():
            fname = request.POST.get("firstName")
            lname = request.POST.get("lastName")
            email = request.POST.get("email")
            address = request.POST.get("address")
            phone = request.POST.get("phoneNumber")
            uname = request.POST.get("username")
            passw = request.POST.get("password")
            cpassw = request.POST.get("cpassword")
            
            if passw == cpassw:
                if Customer.objects.filter(username=uname).exists():
                    messages.info(request,'Username already taken')
                    return redirect('register.html')
                elif Customer.objects.filter(email=email).exists():
                    messages.info(request, 'Email already used')
                    return redirect('register.html')
                else:
                    form = Customer(firstName=fname, lastName=lname, email=email, address=address, phoneNumber=phone, username=uname, password=passw)
                    form.save()
            else:
                return HttpResponse('Password not match')

            # return HttpResponse('Record Saved')
            # print('success')
            return redirect('artcraft:login')
        else:
            # messages.info(request, 'one or more fields are missing inputs')
            return redirect('artcraft:register')
            # return HttpResponse('Not Saved')

class registerArtistView(View):
    def get(self, request):
        return render(request, 'registerArtist.html')
    
    def post(self, request):
        form = ArtistForm(request.POST)

        if form.is_valid():
            fname = request.POST.get("firstName")
            lname = request.POST.get("lastName")
            bDate = request.POST.get("birthDate")
            address = request.POST.get("address")
            phone = request.POST.get("phoneNumber")
            uname = request.POST.get("username")
            passw = request.POST.get("password")

            form = Artist(firstName=fname, lastName=lname, birthDate=bDate, address=address, phoneNumber=phone, username=uname, password=passw)
            form.save()
            

            # return HttpResponse('Record Saved')
            # print('success')
            return redirect('artcraft:login')
        else:
            # messages.info(request, 'one or more fields are missing inputs')
            # return redirect('artcraft:register')
            return HttpResponse('Not Saved')

artcraftV2/artcraftV2/artcraft/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- ======= About Section ======= -->
    <div class="container">
        <div class="row no-gutters">
            <div class="image col-xl-5 justify-content-center justify-content-lg-start">
                <img src="/static/images/logo.png" style="width: 110%; margin-top: 50px; margin-left: 10px;">
            </div>
            <div class="col-xl-7 ps-0 ps-lg-5 pe-lg-1 d-flex align-items-stretch">
                <div class="content d-flex flex-column justify-content-center">
                    <header class="w3-container w3-xlarge">
                        <p class="header">About ARTCRAFT</p>
                      </header>
                    <p>
                    We are students from Cebu Institute of Technology - University that development this website.
                    This website aims to provides a site for artists to sell and showcase their artworks. Artist will be able to sell their artwork through this
                    website. The developers want to encourage Artist to use a convenient and modern way to showcase their artwork and earn money from it.
                    </p>
                    <div class="row">
                    <div class="col-md-6 icon-box">
                        <i class="bx bx-receipt"></i>
                        <h4>Content</h4>
                        <p>This website serve as a Art gallery for inspiring Artists.
                        </p>
                    </div>
                    <div class="col-md-6 icon-box">
                        <i class="bx bx-cube-alt"></i>
                        <h4>Enterprise</h4>
                        <p>The website provides a dashboard that allows to view the artist, customer and order that will
                        will be created. It allows also to manipulate the records in the table. </p>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <footer>
        <div class="w3-pale-blue w3-center w3-padding-24">Copyrights 2021 | ARTCRAFT</div>
    </footer>
    


{% endblock content %}

artcraftV2/artcraftV2/artcraft/templates/artwork.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    
<style>
  img {
    vertical-align: middle;
  }
  
  /* Position the image container (needed to position the left and right arrows) */
  .containnner {
    position: relative;
    height: 100vh;
    width: 100%;
  }
  
  /* Hide the images by default */
  .mySlides {
    display: none;
  }
  
  /* Add a pointer when hovering over the thumbnail images */
  .cursor {
    cursor: pointer;
  }
  
  /* Next & previous buttons */
  .prev,
  .next {
    cursor: pointer;
    position: absolute;
    top: 40%;
    width: auto;
    padding: 16px;
    margin-top: -50px;
    color: white;
    font-weight: bold;
    font-size: 20px;
    border-radius: 0 3px 3px 0;
    user-select: none;
    -webkit-user-select: none;
  }
  
  /* Position the "next button" to the right */
  .next {
    right: 0;
    border-radius: 3px 0 0 3px;
  }
  
  /* On hover, add a black background color with a little bit see-through */
  .prev:hover,
  .next:hover {
    background-color: white;
  }
  
  /* Number text (1/3 etc) */
  .numbertext {
    color: #f2f2f2;
    font-size: 12px;
    padding: 8px 12px;
    position: absolute;
    top: 0;
  }
  
  /* Container for image text */
  .caption-container {
    text-align: center;
    background-color: #222;
    padding: 2px 16px;
    color: white;
  }
  
  .row:after {
    content: "";
    display: table;
    clear: both;
  }
  
  /* Six columns side by side */
  .column {
    float: left;
    width: 16.66%;
  }
  
  /* Add a transparency effect for thumnbail images */
  .demo {
    opacity: 0.6;
  }
  
  .active,
  .demo:hover {
    opacity: 1;
  }
  </style>
  <body>
  <!-- Top header -->
  <header class="w3-container w3-xlarge">
  <p class="header"><strong>Hey! Welcome to our Art Gallery</strong></p>
  </header>
  
  <div class="containnner">
    <div class="mySlides">
      <img src="/static/images/zero hour.jpg" style="width:100%">
    </div>
  
    <div class="mySlides">
      <img src="/static/images/zero hour 1.jpg" style="width:100%">
    </div>
  
    <div class="mySlides">
      <img src="/static/images/zero hour 2.jpg" style="width:100%">
    </div>
      
    <div class="mySlides">
      <img src="/static/images/zero hour 3.jpg" style="width:100%">
    </div>
  
    <div class="mySlides">
      <img src="/static/images/zero hour 4.jpg" style="width:100%">
    </div>
      
    <div class="mySlides">
      <img src="/static/images/zero hour.jpg" style="width:100%">
    </div>
    <a class="prev" onclick="plusSlides(-1)">❮</a>
    <a class="next" onclick="plusSlides(1)">❯</a>
  
    <div class="caption-container">
      <p id="caption"></p>
    </div>
  
    <div class="row">
      <div class="column">
        <img class="demo cursor" src="/static/images/zero hour.jpg" style="width:100%" onclick="currentSlide(1)" alt="The Woods">
      </div>
      <div class="column">
        <img class="demo cursor" src="/static/images/zero hour 1.jpg" style="width:100%" onclick="currentSlide(2)" alt="Cinque Terre">
      </div>
      <div class="column">
        <img class="demo cursor" src="/static/images/zero hour 2.jpg" style="width:100%" onclick="currentSlide(3)" alt="Mountains and fjords">
      </div>
      <div class="column">
        <img class="demo cursor" src="/static/images/zero hour 3.jpg" style="width:100%" onclick="currentSlide(4)" alt="Northern Lights">
      </div>
      <div class="column">
        <img class="demo cursor" src="/static/images/zero hour 4.jpg" style="width:100%" onclick="currentSlide(5)" alt="Nature and sunrise">
      </div>    
      <div class="column">
        <img class="demo cursor" src="/static/images/zero hour.jpg" style="width:100%" onclick="currentSlide(6)" alt="Snowy Mountains">
      </div>
    </div>
  </div>
  
  <script>
  var slideIndex = 1;
  showSlides(slideIndex);
  
  function plusSlides(n) {
    showSlides(slideIndex += n);
  }
  
  function currentSlide(n) {
    showSlides(slideIndex = n);
  }
  
  function showSlides(n) {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("demo");
    var captionText = document.getElementById("caption");
    if (n > slides.length) {slideIndex = 1}
    if (n < 1) {slideIndex = slides.length}
    for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";
    }
    for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex-1].style.display = "block";
    dots[slideIndex-1].className += " active";
    captionText.innerHTML = dots[slideIndex-1].alt;
  }
  </script>
  
  <br><br><br><br><br><br><br><br>
  
  <!-- Product grid -->
  <div class="w3-row w3-grayscale">
    <hr>
    <div class="w3-col l3 s6">
      <div class="w3-container">
        <img src="/static/images/zero hour.jpg" alt="ARTWORK 1"style="width:100%">
        <p>Artwork 1<br><b class="w3-text-red">$24.99</b></p>
      </div>
      <div class="w3-container">
        <img src="/static/images/zero hour 3.jpg" alt="ARTWORK 2" style="width:100%">
        <p>Artwork 2<br><b class="w3-text-red">$19.99</b></p>
      </div>
    </div>

    <div class="w3-col l3 s6">
      <div class="w3-container">
        <div class="w3-display-container">
            <img src="/static/images/zero hour 1.jpg" alt="ARTWORK 3"style="width:100%">
        </div>
        <p>Artwork 3<br><b class="w3-text-red">$19.99</b></p>
      </div>
      <div class="w3-container">
        <img src="/static/images/zero hour 2.jpg" alt="ARTWORK 4" style="width:100%">
        <p>Artwork 4<br><b class="w3-text-red">$20.50</b></p>
      </div>
    </div>

    <div class="w3-col l3 s6">
      <div class="w3-container">
        <img src="/static/images/zero hour 3.jpg" alt="ARTWORK 5" style="width:100%">
        <p>Artwork 5<br><b class="w3-text-red">$20.50</b></p>
      </div>
      <div class="w3-container">
        <div class="w3-display-container">
            <img src="/static/images/zero hour 4.jpg" alt="ARTWORK 6" style="width:100%">
          <div class="w3-display-middle w3-display-hover">
          </div>
        </div>
        <p>Artwork 6<br><b class="w3-text-red">$14.99</b></p>
      </div>
    </div>

    <div class="w3-col l3 s6">
      <div class="w3-container">
        <img src="/static/images/zero hour.jpg" alt="ARTWORK 7" style="width:100%">
        <p>Artwork 7<br><b class="w3-text-red">$14.99</b></p>
      </div>
      <div class="w3-container">
        <img src="/static/images/zero hour 1.jpg" alt="ARTWORK 8" style="width:100%">
        <p>Artwork 8<br><b class="w3-text-red">$24.99</b></p>
      </div>
    </div>
  </div>
  <br>

  <div class="w3-pale-blue w3-center w3-padding-24">Copyrights 2021 | ARTCRAFT</div>

  <!-- End page content -->
</div>

{% endblock content %}

artcraftV2/artcraftV2/artcraft/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
      
    <div class="container">
      <div class="section-title">
        <h2><strong>Contact Us</strong></h2>
        <p>Feel free to communicate with the team!</p>
      </div>
      <div class="form">
        <form action="forms/contact.php" method="post" role="form" class="php-email-form">
          <div class="row">
            <div class="col-md-6 form-group">
              <input type="text" name="name" class="form-control" id="name" placeholder="Enter name" data-rule="minlen:4" data-msg="Please enter at least 4 chars">
            </div>
            <div class="col-md-6 form-group mt-3 mt-md-0">
              <input type="email" class="form-control" name="email" id="email" placeholder="Enter email" data-rule="email" data-msg="Please enter a valid email">
            </div>
          </div>
          <div class="form-group mt-3">
            <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
          </div>
          <div class="form-group mt-3">
            <textarea class="form-control" name="message" rows="10" placeholder="Create message" required></textarea>
          </div>
          
          <div class="text-center"><button class="btn btn-primary" type="submit">Send Message</button></div>
        </form>
      </div>

    </div>
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    <footer>
        <div class="w3-pale-blue w3-center w3-padding-24">Copyrights 2021 | ARTCRAFT</div>
    </footer>
    


{% endblock content %}

artcraftV2/artcraftV2/artcraft/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="homepage">
  <br><br><br><br><br><br><br><br><br>
  <header class="w3-container w3-xlarge">
    <p class="header"><strong>WELCOME {{ firstName }} TO ARTCRAFT</strong></p>
    <h3 style="color: white; text-shadow: 2px 2px black;">Discover the world through artworks!</h3>
    <a href="{% url 'artcraft:artwork' %}">
      <i class='bx bxs-send' style="color: white; margin-left: 50%; font-size: 30px;"></i>
    </a>
    <br>
  </header>
  <br><br><br><br><br><br><br><br><br>
  <footer>
    <div class="w3-pale-blue w3-center w3-padding-24">Copyrights 2021 | ARTCRAFT</div>
  </footer>
</div>

{% endblock content %}

artcraftV2/artcraftV2/artcraft/templates/login.html
{% extends 'base.html' %}

{% block content %}

    {% csrf_token %}
    
<div class="wrapper">
        <div class="logo">
                <img src="/static/images/logo.png" style="width:35%; margin-left: 36%;">
        </div>
        <form method="POST">
        {% csrf_token %}
                <div class="input-data">
                        <input type="text" name="username" required="required">
                        <div class="underline"></div>
                                <label>Username</label>
                        </div>
        
                        <br>
        
                <div class="input-data">
                        <input type="password" name="password" required="required">
                        <div class="underline"></div>
                        <label>Password</label>
                </div>
                        <br>
        
                <div class="textfield">
                        <input type="checkbox" checked="checked" name="remember"/>
                        Remember Password
                </div>

                        <br>
                        {% if messages %}
                        {% for message in messages %}
                        <div class="error-messages">
                                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                                {{message}}
                        </div>
                        {% endfor %}
                        {% endif %}
                        <br>
                        <button class="loginbutton" type="submit">LOGIN</button>

                        <div class="signup">
                                Don't have an account yet?
                                <a href="{% url 'artcraft:register' %}" style="color: blue;">Create one</a>
                                <br>
                                Are you an <strong>Artist</strong>?
                                <a href="{% url 'artcraft:registerArtist' %}" style="color: blue;">Sign up</a>
                        </div>
        
                        <div class="psw">
                                <a href="#">Forgot Password?</a>
                        </div>   
                </div>
        </form>
</div>

{% endblock content %}

artcraftV2/artcraftV2/artcraft/templates/register.html
{% extends 'base.html' %}

{% block content %} 

<div class="container">
    <div class="title">SIGN UP</div>
    <div class="tagline">It's quick and easy.</div>
    <div class="content">
      <form method="POST">
        {% csrf_token %}
        <div class="user-details">
          <div class="input-box">
            <span class="details">First Name</span>
            <input type="text" name="firstName" placeholder="Enter your first name" required="required">
          </div>
          <div class="input-box">
            <span class="details">Last Name</span>
            <input type="text" name="lastName" placeholder="Enter your last name" required="required">
          </div>
          <div class="input-box">
            <span class="details">Username</span>
            <input type="text" name="username" placeholder="Must be more than 4 characters" required="required">
          </div>
          <div class="input-box">
            <span class="details">Email</span>
            <input type="email" name="email" placeholder="Enter your email" required="required">
          </div>
          <div class="input-box">
            <span class="details">Contact Number</span>
            <input type="text" name="phoneNumber" placeholder="Enter your number" required="required">
          </div>
          <div class="input-box">
            <span class="details">Address</span>
            <input type="text" name="address" placeholder="Enter your address" required="required">
          </div>
          <div class="input-box">
            <span class="details">Password</span>
            <input type="password" name="password" placeholder="Password must be 8 characters long" required="required">
          </div>
          <div class="input-box">
            <span class="details">Confirm Password</span>
            <input type="password" name="cpassword" placeholder="Confirm your password" required="required">
          </div>
        </div>
       
        <!-- {% if messages %}
        {% for message in messages %} 
        <div class="error-message">
            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
            {{message}}
        </div>
        {% endfor %}
        {% endif %} -->
        <div class="button">
          <input type="submit" value="Register">
        </div>
      </form>

        <div class="signin">
          Already have an account?
          <a href="{% url 'artcraft:login' %}">Sign in</a>
        </div>
      
    </div>
  </div>
</div>

{% endblock content %}

artcraftV2/artcraftV2/artcraft/templates/registerArtist.html
{% extends 'base.html' %}

{% block content %} 

<div class="container">
    <div class="title">SIGN UP AS AN ARTIST!</div>
    <div class="tagline">Flex your works and auction them!</div>
    <div class="content">
      <form method="POST">
        {% csrf_token %}
        <div class="user-details">
          <div class="input-box">
            <span class="details">First Name</span>
            <input type="text" name="firstName" placeholder="Enter your first name" required="required">
          </div>
          <div class="input-box">
            <span class="details">Last Name</span>
            <input type="text" name="lastName" placeholder="Enter your last name" required="required">
          </div>
          <div class="input-box">
            <span class="details">Username</span>
            <input type="text" name="username" placeholder="Must be more than 4 characters" required="required">
          </div>
          <div class="input-box">
            <span class="details">Birth Date</span>
            <input type="text" name="birthDate" placeholder="Enter your birthday" required="required">
          </div>
          <div class="input-box">
            <span class="details">Contact Number</span>
            <input type="text" name="phoneNumber" placeholder="Enter your number" required="required">
          </div>
          <div class="input-box">
            <span class="details">Address</span>
            <input type="text" name="address" placeholder="Enter your address" required="required">
          </div>
          <div class="input-box">
            <span class="details">Password</span>
            <input type="password" name="password" placeholder="Password must be 8 characters long" required="required">
          </div>
          <div class="input-box">
            <span class="details">Confirm Password</span>
            <input type="password" name="confirmPassword" placeholder="Confirm your password" required="required">
          </div>
        </div>
       
        <!-- {% if messages %}
        {% for message in messages %} 
        <div class="error-message">
            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
            {{message}}
        </div>
        {% endfor %}
        {% endif %} -->
        <div class="button">
          <input type="submit" value="Register">
        </div>
      </form>
      
        <div class="signin">
          Already have an account?
          <a href="{% url 'artcraft:login' %}">Sign in</a>
        </div>
      
    </div>
  </div>
</div>

{% endblock content %}